/**
 * Alert Manager API Spec
 * Alert Manager API spec. This spec represents the Alert Management service whose current objective is to prioritize the alerts based upon context.  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@dassana.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CSP } from './cSP';
import { Category } from './category';
import { ResourceType } from './resourceType';
import { RiskRank } from './riskRank';
import { Service } from './service';
import { SubCategory } from './subCategory';
import { Vendors } from './vendors';

export interface DassanaPolicy { 
    id: string;
    csp: CSP;
    service: Service;
    resourceType?: ResourceType;
    category: Category;
    subCategory: SubCategory;
    vendors: Vendors;
    defaultRiskRank?: RiskRank;
    /**
     * this object is available only if alertId was provided
     */
    alertDetails?: any;
}