/**
 * Dassana Org Manager Service
 * This service is responsible for all things org management - org, teams, members. Note that in the context of this service, a user is a member
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BaseProfile } from './baseProfile';
import { FirstName } from './firstName';
import { LastName } from './lastName';
import { MemberTeamsSummary } from './memberTeamsSummary';
import { Persona } from './persona';
import { TeamSummary } from './teamSummary';
import { Timezone } from './timezone';
import { User } from './user';

export interface Member extends User { 
    workStart?: number;
    workEnd?: number;
    timeZone?: Timezone;
    personas?: Array<Persona>;
    firstName?: string;
    lastName?: string;
    teams?: Array<TeamSummary>;
}