/**
 * Alert Manager API Spec
 * Alert Manager API spec. This spec represents the Alert Management service whose current objective is to prioritize the alerts based upon context.  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@dassana.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Condition } from './condition';
import { RiskRank } from './riskRank';

export interface Rule { 
    id: string;
    name?: string;
    operator: Rule.OperatorEnum;
    conditions: Array<Condition>;
    riskRank?: RiskRank;
    /**
     * this is set to true if the rule was matched
     */
    matched?: boolean;
}
export namespace Rule {
    export type OperatorEnum = 'and' | 'or';
    export const OperatorEnum = {
        And: 'and' as OperatorEnum,
        Or: 'or' as OperatorEnum
    };
}