/**
 * Orders API Test
 * This is a sample Orders API based on the Orders demo from [https://smartbear.com/](https://smartbear.com). 
 *
 * OpenAPI spec version: 2
 * Contact: test@smartbear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class AllOrders (
) extends ApiModel


