/**
 * Orders API Test
 * This is a sample Orders API based on the Orders demo from [https://smartbear.com/](https://smartbear.com). 
 *
 * OpenAPI spec version: 2
 * Contact: test@smartbear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Order (
  orderID: Option[Int] = None,
  customerName: Option[String] = None,
  product: Option[String] = None,
  quantity: Option[Int] = None,
  orderDate: Option[DateTime] = None,
  street: Option[String] = None,
  city: Option[String] = None,
  state: Option[String] = None,
  expirationDate: Option[DateTime] = None
) extends ApiModel


