swagger: '2.0'
info:
  description: This is a simple API
  version: 1.0.0
  title: Simple Inventory API
  # put the contact info for your development or API team
  contact:
    email: you@your-company.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers

paths:
  /inventory:
    get:
      tags:
      - developers
      summary: searches inventory
      operationId: searchInventory
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      produces:
      - application/json
      parameters:
      - in: query
        name: searchString
        description: pass an optional search string for looking up inventory
        required: false
        type: string
      - in: query
        name: skip
        description: number of records to skip for pagination
        type: integer
        format: int32
        minimum: 0
      - in: query
        name: limit
        description: maximum number of records to return
        type: integer
        format: int32
        minimum: 0
        maximum: 50
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/InventoryItem'
          headers:
            X-RateLimit-Limit:
              type: integer
              description: Request limit per hour.
            X-RateLimit-Reset:
              type: string
              format: date-time
              description: The UTC date/time at which the current 
        400:
          description: bad input parameter
    post:
      summary: adds an inventory item
      operationId: addInventory
      description: Adds an item to the system
      #consumes:
      #- application/json
      #produces:
      #- application/json
      parameters:
      - in: body
        name: inventoryItem
        description: Inventory item to add
        schema:
          type: object
          example: 
            "200": 
              {"asset_content_hash":"3457258287920120451","asset_ocr_settings":"28.16","asset_ocr_text":"EXPLORE CUBA WITH FREE UNLIMITED SHORE EXCURSIONS VIEW VOYAGES", "asset_original_ext":"JPG","asset_original_snapshot":"https://tdc-smxysnpx.s3.amazonaws.com/D41E-5C5B-D728-6846/345728287920120451.jpg","asset_original_url":"https://www.rssc.com/sites/default/files/Cuba_2019-2020Voyages_desktop_0.jpg","asset_original_url_hash":"12091859026330469603","asset_original_word_count":"10","asset_replacement_status":"ocrtext", "asset_replacement_url":"","asset_transcription_text":"","context_url":"https://www.rssc.com/","context_url_hash":"12638123428881205758","created_utc":"2018-11-26 12:43:24","lastmod_utc":"2018-11-26 12:43:26", "user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/605.1 (KHTML, like gecko) JavaFX/10 Safari/605.1 Periscope/1.0"}
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
            
      responses:
        200:
          description: OK
          examples:
            application/json: {
              '200':
                  {"asset_content_hash":"3457258287920120451","asset_ocr_settings":"28.16","asset_ocr_text":"EXPLORE CUBA WITH FREE UNLIMITED SHORE EXCURSIONS VIEW VOYAGES", "asset_original_ext":"JPG","asset_original_snapshot":"https://tdc-smxysnpx.s3.amazonaws.com/D41E-5C5B-D728-6846/345728287920120451.jpg","asset_original_url":"https://www.rssc.com/sites/default/files/Cuba_2019-2020Voyages_desktop_0.jpg","asset_original_url_hash":"12091859026330469603","asset_original_word_count":"10","asset_replacement_status":"ocrtext", "asset_replacement_url":"","asset_transcription_text":"","context_url":"https://www.rssc.com/","context_url_hash":"12638123428881205758","created_utc":"2018-11-26 12:43:24","lastmod_utc":"2018-11-26 12:43:26", "user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/605.1 (KHTML, like gecko) JavaFX/10 Safari/605.1 Periscope/1.0"}
            }
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists
definitions:
  InventoryItem:
    type: object
    required:
    - id
    - name
    - manufacturer
    - releaseDate
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      name:
        type: string
        example: Widget Adapter
      releaseDate:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
      manufacturer:
        $ref: '#/definitions/Manufacturer'
  Manufacturer:
    required:
    - name
    properties:
      name:
        type: string
        example: ACME Corporation
      homePage:
        type: string
        format: url
        example:  https://www.acme-corp.com
      phone:
        type: string
        example: 408-867-5309
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /Julia_org/Julia00324161/1.0.0
schemes:
 - https
x-aws-api-id: 'pt3w4qtxcg'